### ISSUE TITLE
The steamworks is private .git is private I can't build it easily

### ISSUE THREAD

**Issue by karl-police** [Trico-Everfire/p2-publishing-tool#28]
:(

**Comment by Trico-Everfire** [comment]
This is because of Steamworks's agreement, I cannot provide the steamworks SDK myself, that'd go against the agreement. It is a thing you have to download to allow you to build it yourself. As to download it, you need to log into steamworks with your steam account. Kinda stupid. I know, but I cannot provide the steamworks SDK, sorry!
