### ISSUE TITLE
"Steam must be running" (release)

### ISSUE THREAD

**Issue by FalconinVoid** [Trico-Everfire/p2-publishing-tool#29]
"Steam must be running to use this tool (SteamAPI_Init() failed)."

**Comment by Trico-Everfire** [comment]
Use the release version, I do not provide the debug version of QT binaries.

**Comment by FalconinVoid** [comment]
Okay, but the release version can't find Steam anymore: "Steam must be running to use this tool (SteamAPI_Init() failed)."
Do you know, how to solve the problem? (I started Steam before I opened the tool of course)

**Comment by Trico-Everfire** [comment]
it CAN fail for multiple reasons, 99% it's because Steam isn't running. the other 1% are edgecases.

**Comment by Trico-Everfire** [comment]
The thing is that, for me the map uploader works fine. If restarting your computer doesn't work then the problem lays way deeper than I thought. Debugging the application on Windiows is quite difficult for me, because I don't own a Windows system, at least, not one that I haven't tested already (the tool works on it). so... I'll see what I can do.

**Comment by Trico-Everfire** [comment]
I've had 2 separate Windows users confirm that the tool works, it's likely something wrong with your machine. Make sure steam is running, update steam and ensure Portal 2 is installed.

**Comment by FalconinVoid** [comment]
Okay that's really weird, I'll try it on another machine. The last Steam update was on the 7th March 2024, Portal 2 is installed and Steam is running ofc.

**Comment by Trico-Everfire** [comment]
The thing is that, The Steam API does NOT update, ever, if it were to, a lot of legacy applications Valve and other Steam users have made in the past would break, with no one to maintain those tools it's Valve's number 1 priority is to never change the legacy Steam API, which this tool relies on because Portal 2 relies on it. besides just setting the application theming and env variables the first piece of code that runs is:
```c++
	if ( !SteamAPI_Init() )
	{
	...
	}
```

It may be that your computer does not allow applications to set env variables, though, I doubt that. However, if it is indeed the case. You need to put this file at the same location as the .exe

[steam_appid.txt](https://github.com/Trico-Everfire/p2-publishing-tool/files/14560012/steam_appid.txt)

I cannot guarenteee it'd fix it, but it'd be worth a shot.

**Comment by FalconinVoid** [comment]
I tried that, but unfortuntately, this also doesn't work.

**Comment by FalconinVoid** [comment]
Do I have to put the folder in a special directory? Like bin?

**Comment by FalconinVoid** [comment]
I tried reinstalling Steam but that also didn't work :(

**Comment by Trico-Everfire** [comment]
This might be a redundant question, but do you have Portal 2 installed? And if so, is it on your main drive or a secondary drive?

**Comment by FalconinVoid** [comment]
I tried installing Portal 2 on both drives, but this also didn't work.

**Comment by Trico-Everfire** [comment]
What happens if you run the map uploader from the command prompt?
Does that show anything?

**Comment by FalconinVoid** [comment]
No, running it from the admin command prompt doesn't work either.

**Comment by FalconinVoid** [comment]
Fixed the problem now. But it was so stupid, I don't want to talk about it... :|
